### ISSUE TITLE
As a player, I want the host of a lobby to start a game for everyone so that all players, synchronously, have an equal amount of time to answer a randomly generated question.

### ISSUE THREAD

**Issue by HarrisonHutton** [samarthjj/CSE-442-Group-Project#55]
**Acceptance Tests**

*Test 1* **(Clock ticks to zero before moving on)**
1) Navigate to http://minorprophets.tech/
2) Log in with username: **`zenhub1`** and password: **`Apple123*`** (Call this account *Player A*)
3) In a new tab, navigate to http://minorprophets.tech/
4) Login with the username: **`zenhub2`** and password: **`Apple123*`** (Call this account *Player B*)
5) Start a new game by pressing "Start New Game" on Player A's tab
6) Join this newly created game on Player B's tab by using the game code from Player A's current tab
7) Ignore the genre selection buttons and press "Start Game" on Player A's tab
8) In the top-right of the newly-loaded screen (on both tabs), see that the timer is correctly ticking down by one second every second
9) Let the clock tick to 0 from 30
10) Observe, on both tabs, that we are now on a screen displaying the correct answer to the previous question.

*Test 2* **(Player clicks "Quit" before the clock hits zero)**
1) Navigate to http://minorprophets.tech/
2) Log in with username: **`zenhub1`** and password: **`Apple123*`** (Call this account *Player A*)
3) In a new tab, navigate to http://minorprophets.tech/
4) Login with the username: **`zenhub2`** and password: **`Apple123*`** (Call this account *Player B*)
5) Start a new game by pressing "Start New Game" on Player A's tab
6) Join this newly created game on Player B's tab by using the game code from Player A's current tab
7) Ignore the genre selection buttons and press "Start Game" on Player A's tab
8) In the top-right of the newly-loaded screen (on both tabs), see that the timer is correctly ticking down by one second every second
9) Before the clock has finished ticking to 0, move to the next step
10) Click the "Quit" button on Player A and Player B's screens
11) The screen should correctly revert back to the homepage with the "Start New Game" and "Join Game" buttons for both players

**Comment by ProfMatthewHz** [comment]
Get rid of the *UNRELEASED TO CUSTOMER* in the title -- that fact is clear from this not being closed yet. Every user story needs to have a role, action, and observable outcome. What is the action in this story? What is the observable outcome? As an outsider, I have no idea what this is going to do. Would this be a correct explanation:
_As someone who likes balanced play, I want the host to start a game for everyone so that all of the players' timers are synchronized._

Test issues:
Do not make your user think -- just tell them the account to use. If there are differences between the accounts, make this into three different tests (e.g., 1 per account).
How do I "Join a New Game"? Always assume your user has an IQ of 0. (All too real, sadly)
Because the story does not clearly explain what this feature is, the test is equally muddled. Let's get to a good user story and the rest of this will follow.

**Comment by ProfMatthewHz** [comment]
As an untrained user, I have a pretty good idea of how long a second is. Please do not ask me to use a second webpage to verify this info.

Why does the game include the option for someone to rage quit? What is the role of the countdown done button? How are these related to the current feature and, if they are not, why are you testing them here?

**Comment by ProfMatthewHz** [comment]
We can talk about this tomorrow (and your tests are getting much better) but I am still uncertain what a few of the steps mean.

**Comment by HarrisonHutton** [comment]
I removed the test having to do with the countdown done button since it will no longer be in the game.
