### ISSUE TITLE
Add alert if the room owner does not select a number of rounds

### ISSUE THREAD

**Issue by MaeveRositzke** [samarthjj/CSE-442-Group-Project#59]
**Task Tests**

*Test 1*
1) Go to http://minorprophets.tech/ or run the app locally
2) Use username: "zenhub1" and password: "Apple123\*" as login credentials
3) Click "Login"
4) Click "Start New Game"
5) Do not select the number of rounds
6) Confirm that none of the round number choices are highlighted
7) Click "Start Game"
8) Confirm that you do not go to the 1st question screen
9) Confirm that you see an alert box displayed as a result of calling the alert() function telling you to pick a round number

*Test 2*
1) Go to http://minorprophets.tech/ or run the app locally
2)  Use username: "zenhub1" and password: "Apple123\*" as login credentials
3) Click "Login"
4) Click "Start New Game"
5) Do not select the number of rounds
6) Confirm that none of the round number choices are highlighted
7) Go to http://minorprophets.tech/ in a different browser to simulate a second player
8) Use username: "zenhub2" and password: "Apple123/*" as login credentials
9) Click "Login"
10) Enter the roomcode
11) Click "Join Game"
12) In the _first_ browser, click "Start Game"
13) In the _second_ browser, confirm that you do not go to the 1st question screen

**Comment by ProfMatthewHz** [comment]
Be specific in your tests. Since this is a task test, what is the name, ID, or other selector being used for the HTML element in which the error appears? That is the information needed so that this task could be coded in parallel with the front-end.

This task is only about the error for not selecting a number of rounds. You can actually ditch the tests dealing with handling correct data entries -- that work belongs to a different task.
